/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.NhanVienDAO;
import com.edusys.model.NhanVien;
import com.edusys.utils.XAuth;
import com.edusys.utils.XDialog;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.net.URI;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;

/**
 *
 * @author duyplus
 */
public class DangNhapJD extends javax.swing.JDialog {

    NhanVienDAO nvdao = new NhanVienDAO();

    /**
     * Creates new form DangNhapJDialog
     *
     * @param parent
     * @param modal
     */
    public DangNhapJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    private void login() {
        String manv = txtMaNV.getText();
        String mk = new String(txtMatKhau.getPassword());
        NhanVien nv = nvdao.selectById(manv);
        if (nv == null) {
            XDialog.alert(this, "Sai tên đăng nhập!");
        } else if (!mk.equals(nv.getMatKhau())) {
            XDialog.alert(this, "Sai mật khẩu!");
        } else {
            System.out.println("Logged in successfully...");
            XDialog.alert(this, "Đăng nhập thành công!");
            XAuth.user = nv;
            this.dispose();
        }
    }

    private void introduce() {
        new GioiThieuJD(new javax.swing.JFrame(), true).setVisible(true);
    }

    private void exit() {
        if (XDialog.confirm(this, "Bạn muốn kết thúc ứng dụng?")) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlDangNhap = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblUserIcon = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblUser1 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblPassword = new javax.swing.JLabel();
        lblPassword1 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        lblhide = new javax.swing.JLabel();
        lblshow = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pnlInfo = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jpnlDangNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 141, 120)));

        pnlLogin.setBackground(new java.awt.Color(228, 246, 250));
        pnlLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(228, 141, 120), 1, true));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-users.png"))); // NOI18N
        pnlLogin.add(lblUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, 100));

        lblUser.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(238, 112, 82));
        lblUser.setText("Tài khoản:");
        pnlLogin.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, -1));

        lblUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-user.png"))); // NOI18N
        pnlLogin.add(lblUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 40));

        txtMaNV.setBackground(new java.awt.Color(228, 246, 250));
        txtMaNV.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        txtMaNV.setForeground(new java.awt.Color(250, 102, 0));
        txtMaNV.setToolTipText("Tài khoản");
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });
        txtMaNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaNVKeyPressed(evt);
            }
        });
        pnlLogin.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 160, 40));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pnlLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 260, 20));

        lblPassword.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(238, 112, 82));
        lblPassword.setText("Mật khẩu:");
        pnlLogin.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, -1));

        lblPassword1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-key.png"))); // NOI18N
        pnlLogin.add(lblPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 380, -1, 40));

        txtMatKhau.setBackground(new java.awt.Color(228, 246, 250));
        txtMatKhau.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(250, 102, 0));
        txtMatKhau.setToolTipText("Mật khẩu");
        txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatKhauKeyPressed(evt);
            }
        });
        pnlLogin.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 160, 40));

        lblhide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhideMouseClicked(evt);
            }
        });
        pnlLogin.add(lblhide, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 40, 20));

        lblshow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblshowMouseClicked(evt);
            }
        });
        pnlLogin.add(lblshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 40, 20));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-show.png"))); // NOI18N
        pnlLogin.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 20, 20));

        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pnlLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 260, 20));

        btnLogin.setBackground(new java.awt.Color(0, 95, 95));
        btnLogin.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-login.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setBorderPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 120, 45));

        btnCancel.setBackground(new java.awt.Color(0, 95, 95));
        btnCancel.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorderPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlLogin.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 120, 45));

        btnReset.setBackground(new java.awt.Color(51, 69, 72));
        btnReset.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-forgot.png"))); // NOI18N
        btnReset.setText("Forgot Password?");
        btnReset.setBorderPainted(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        pnlLogin.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 260, 45));

        pnlInfo.setBackground(new java.awt.Color(228, 246, 250));
        pnlInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(228, 141, 120), 1, true));

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        pnlTitle.setBackground(new java.awt.Color(51, 51, 255));
        pnlTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 105, 0)));
        pnlTitle.setPreferredSize(new java.awt.Dimension(700, 68));

        lblTitle.setFont(new java.awt.Font("Be Vietnam Pro", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("PHẦN MỀM QUẢN LÝ HỌC VIÊN");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(81, 81, 81))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnlDangNhapLayout = new javax.swing.GroupLayout(jpnlDangNhap);
        jpnlDangNhap.setLayout(jpnlDangNhapLayout);
        jpnlDangNhapLayout.setHorizontalGroup(
            jpnlDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDangNhapLayout.createSequentialGroup()
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jpnlDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)))
        );
        jpnlDangNhapLayout.setVerticalGroup(
            jpnlDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDangNhapLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpnlDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnlDangNhapLayout.createSequentialGroup()
                        .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaNVKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.getRootPane().setDefaultButton(btnLogin);
            btnLogin.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.exit();
        }
    }//GEN-LAST:event_txtMaNVKeyPressed

    private void txtMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.getRootPane().setDefaultButton(btnLogin);
            btnLogin.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.exit();
        }
    }//GEN-LAST:event_txtMatKhauKeyPressed

    private void lblhideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhideMouseClicked
        // TODO add your handling code here:
        lblshow.setVisible(true);
        lblshow.setEnabled(true);
        txtMatKhau.setEchoChar((char) 0);
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/edusys/icons/icons8-hide.png"));
        lblIcon.setIcon(icon);
        lblhide.setVisible(false);
        lblhide.setEnabled(false);
    }//GEN-LAST:event_lblhideMouseClicked

    private void lblshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblshowMouseClicked
        // TODO add your handling code here:
        lblhide.setVisible(true);
        lblhide.setEnabled(true);
        txtMatKhau.setEchoChar((char) 8226);
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/edusys/icons/icons8-show.png"));
        lblIcon.setIcon(icon);
        lblshow.setVisible(false);
        lblshow.setEnabled(false);
    }//GEN-LAST:event_lblshowMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (txtMaNV.getText().trim().length() > 0) {
            if (txtMatKhau.getPassword().length > 0) {
                this.login();
            } else {
                XDialog.alert(this, "Không được để trống tên mật khẩu.");
            }
        } else {
            XDialog.alert(this, "Không được để trống tên đăng nhập.");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.exit();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ForgotJD(new javax.swing.JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReset;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpnlDangNhap;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUser1;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JLabel lblhide;
    private javax.swing.JLabel lblshow;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhau;
    // End of variables declaration//GEN-END:variables
}
