/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.QuenMKDAO;
import com.edusys.utils.XDialog;

/**
 *
 * @author duyplus
 */
public class ForgotJD extends javax.swing.JDialog {

    /**
     * Creates new form ChaoJDialog
     *
     * @param parent
     * @param modal
     */
    public ForgotJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    private void resetPass() {
        try {
            QuenMKDAO qmk = new QuenMKDAO();
            qmk.update(txtEmail.getText());
            qmk.sendmail(txtEmail.getText());

            System.out.println("The e-mail has been sent successfully!");
            XDialog.alert(this, "Email đã được gửi thành công. Vui lòng kiểm tra ngay!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblEmailIcon = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnReset = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModal(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(228, 246, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 141, 120), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-mailing.png"))); // NOI18N
        jPanel1.add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 100, 100));

        lblEmail.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(238, 112, 82));
        lblEmail.setText("Địa chỉ email:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 140, -1));

        lblEmailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-email-sign.png"))); // NOI18N
        jPanel1.add(lblEmailIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, 40));

        txtEmail.setBackground(new java.awt.Color(228, 246, 250));
        txtEmail.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(250, 105, 0));
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 280, 40));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 290, 20));

        btnReset.setBackground(new java.awt.Color(0, 95, 95));
        btnReset.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-send.png"))); // NOI18N
        btnReset.setText("Gửi thư");
        btnReset.setBorder(null);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 130, 45));

        btnCancel.setBackground(new java.awt.Color(0, 95, 95));
        btnCancel.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-back.png"))); // NOI18N
        btnCancel.setText("Quay lại");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 130, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        this.resetPass();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DangNhapJD(new javax.swing.JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailIcon;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
