/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.utils.XAuth;
import com.edusys.utils.XDate;
import com.edusys.utils.XDialog;
import com.edusys.utils.XImage;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;

/**
 *
 * @author duyplus
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainUI() {
        initComponents();
        init();
    }

    private void init() {
        setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);

        new ChaoJD(this, true).setVisible(true);
        new DangNhapJD(this, true).setVisible(true);
        this.startDongHo();
    }

    public void startDongHo() {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss a");
        new javax.swing.Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo.setText(sdf.format(XDate.now()));
            }
        }).start();
    }

    public void openChuyenDe() {
        if (XAuth.isLogin()) {
            new QLChuyenDeJD(this, true).setVisible(true);
        } else {
            XDialog.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    public void openHocVien() {
        if (XAuth.isLogin()) {
            new QLHocVienJD(this, true).setVisible(true);
        } else {
            XDialog.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    public void openKhoaHoc() {
        if (XAuth.isLogin()) {
            new QLKhoaHocJD(this, true).setVisible(true);
        } else {
            XDialog.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    public void openNguoiHoc() {
        if (XAuth.isLogin()) {
            new QLNguoiHocJD(this, true).setVisible(true);
        } else {
            XDialog.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    public void openNhanVien() {
        if (XAuth.isLogin()) {
            new QLNhanVienJD(this, true).setVisible(true);
        } else {
            XDialog.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    public void openThongKe(int index) {
        if (XAuth.isLogin()) {
            if (index == 3 && !XAuth.isManager()) {
                XDialog.alert(this, "Chỉ trưởng phòng mới được phép xem thông tin doanh thu.");
                return;
            }
            QLThongKeJD qltk = new QLThongKeJD(this, true);
            qltk.selectTab(index);
            qltk.setVisible(true);
        } else {
            XDialog.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    public void openGioiThieu() {
        new GioiThieuJD(this, true).setVisible(true);
    }

    public void openHuongDan() {
        try {
            Desktop.getDesktop().browse(new java.io.File("help/index.html").toURI());
        } catch (Exception e) {
            XDialog.alert(this, "Không tìm thấy file hướng dẫn!");
        }
    }

    public void openDoiMatKhau() {
        if (XAuth.isLogin()) {
            new DoiMatKhauJD(this, true).setVisible(true);
        } else {
            XDialog.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    public void logout() {
        XAuth.clear();
        XDialog.alert(this, "Bạn đã đăng xuất\nVui lòng đăng nhập để sử dụng!");
        new DangNhapJD(this, true).setVisible(true);
    }

    public void exit() {
        if (XDialog.confirm(this, "Bạn có muốn kết thúc phiên làm việc không?")) {
            System.exit(0);
        }
    }

    public void setColor(javax.swing.JPanel panel) {
        panel.setBackground(new Color(197, 197, 197));
    }

    public void resetColor(javax.swing.JPanel panel) {
        panel.setBackground(new Color(0, 245, 232));
    }

    public void setFore(javax.swing.JLabel label) {
        label.setForeground(new Color(0, 0, 255));
    }

    public void resetFore(javax.swing.JLabel label) {
        label.setForeground(new Color(255, 102, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        RightClick = new javax.swing.JMenuItem();
        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblPoly = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        pnlNhanVien = new javax.swing.JPanel();
        lblIconNV = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        pnlChuyenDe = new javax.swing.JPanel();
        lblIconCD = new javax.swing.JLabel();
        lblChuyenDe = new javax.swing.JLabel();
        pnlNguoiHoc = new javax.swing.JPanel();
        lblIconNN = new javax.swing.JLabel();
        lblNguoiHoc = new javax.swing.JLabel();
        pnlHocVien = new javax.swing.JPanel();
        lblIconHV = new javax.swing.JLabel();
        lblHocVien = new javax.swing.JLabel();
        pnlKhoaHoc = new javax.swing.JPanel();
        lblIconKH = new javax.swing.JLabel();
        lblKhoaHoc = new javax.swing.JLabel();
        pnlThongKe = new javax.swing.JPanel();
        lblIconTK = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        pnlDoiMK = new javax.swing.JPanel();
        lblIconDMK = new javax.swing.JLabel();
        lblDoiMK = new javax.swing.JLabel();
        pnlDangXuat = new javax.swing.JPanel();
        lblDX = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        pnlKetThuc = new javax.swing.JPanel();
        lblIconKT = new javax.swing.JLabel();
        lblKetThuc = new javax.swing.JLabel();
        pnlGioiThieu = new javax.swing.JPanel();
        lblIconGT = new javax.swing.JLabel();
        lblGioiThieu = new javax.swing.JLabel();
        pnlDongHo = new javax.swing.JPanel();
        lblIconTG = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();

        RightClick.setFont(new java.awt.Font("Be Vietnam Pro", 2, 12)); // NOI18N
        RightClick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/funny.png"))); // NOI18N
        RightClick.setText("CHÚC BẠN HỌC TẬP TỐT");
        popupMenu.add(RightClick);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ SÁCH");
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlMain.setBackground(new java.awt.Color(228, 246, 250));
        pnlMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 102, 0), 2));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(153, 153, 255));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-home.png"))); // NOI18N

        lblPoly.setFont(new java.awt.Font("Be Vietnam Pro", 1, 36)); // NOI18N
        lblPoly.setForeground(new java.awt.Color(255, 255, 255));
        lblPoly.setText("LapTrinhCity - EduSys");

        lblName.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Phần Mềm Quản Lý Đào Tạo");

        lblExit.setFont(new java.awt.Font("Be Vietnam Pro", 1, 24)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        lblTenNV.setFont(new java.awt.Font("Be Vietnam Pro", 1, 13)); // NOI18N
        lblTenNV.setForeground(new java.awt.Color(255, 255, 255));
        lblTenNV.setText("Mã nhân viên:");

        lblVaiTro.setFont(new java.awt.Font("Be Vietnam Pro", 1, 13)); // NOI18N
        lblVaiTro.setForeground(new java.awt.Color(255, 255, 255));
        lblVaiTro.setText("Chức vụ:");

        lblMinimize.setFont(new java.awt.Font("Be Vietnam Pro", 1, 28)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("−");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblPoly))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblExit)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlHeaderLayout.createSequentialGroup()
                            .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlHeaderLayout.createSequentialGroup()
                            .addComponent(lblPoly)
                            .addGap(18, 18, 18)
                            .addComponent(lblName))))
                .addGap(50, 50, 50))
        );

        pnlMain.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 150));

        pnlNhanVien.setBackground(new java.awt.Color(0, 245, 232));
        pnlNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseExited(evt);
            }
        });

        lblIconNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-nhanvien.png"))); // NOI18N

        lblNhanVien.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(255, 102, 0));
        lblNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhanVienLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lblIconNV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblIconNV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNhanVien)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMain.add(pnlNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 150, 130));

        pnlChuyenDe.setBackground(new java.awt.Color(0, 245, 232));
        pnlChuyenDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlChuyenDeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlChuyenDeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlChuyenDeMouseExited(evt);
            }
        });

        lblIconCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-chuyende.png"))); // NOI18N

        lblChuyenDe.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        lblChuyenDe.setForeground(new java.awt.Color(255, 102, 0));
        lblChuyenDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuyenDe.setText("Chuyên đề");

        javax.swing.GroupLayout pnlChuyenDeLayout = new javax.swing.GroupLayout(pnlChuyenDe);
        pnlChuyenDe.setLayout(pnlChuyenDeLayout);
        pnlChuyenDeLayout.setHorizontalGroup(
            pnlChuyenDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChuyenDeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblIconCD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChuyenDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChuyenDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlChuyenDeLayout.setVerticalGroup(
            pnlChuyenDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChuyenDeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblIconCD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChuyenDe)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMain.add(pnlChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 150, 130));

        pnlNguoiHoc.setBackground(new java.awt.Color(0, 245, 232));
        pnlNguoiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNguoiHocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNguoiHocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNguoiHocMouseExited(evt);
            }
        });

        lblIconNN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-nguoihoc.png"))); // NOI18N

        lblNguoiHoc.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        lblNguoiHoc.setForeground(new java.awt.Color(255, 102, 0));
        lblNguoiHoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNguoiHoc.setText("Người học");

        javax.swing.GroupLayout pnlNguoiHocLayout = new javax.swing.GroupLayout(pnlNguoiHoc);
        pnlNguoiHoc.setLayout(pnlNguoiHocLayout);
        pnlNguoiHocLayout.setHorizontalGroup(
            pnlNguoiHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoiHocLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblIconNN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(pnlNguoiHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNguoiHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNguoiHocLayout.setVerticalGroup(
            pnlNguoiHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoiHocLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblIconNN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNguoiHoc)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMain.add(pnlNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 150, 130));

        pnlHocVien.setBackground(new java.awt.Color(0, 245, 232));
        pnlHocVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHocVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHocVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHocVienMouseExited(evt);
            }
        });

        lblIconHV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-hocvien.png"))); // NOI18N

        lblHocVien.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        lblHocVien.setForeground(new java.awt.Color(255, 102, 0));
        lblHocVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHocVien.setText("Học viên");

        javax.swing.GroupLayout pnlHocVienLayout = new javax.swing.GroupLayout(pnlHocVien);
        pnlHocVien.setLayout(pnlHocVienLayout);
        pnlHocVienLayout.setHorizontalGroup(
            pnlHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHocVienLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblIconHV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHocVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHocVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHocVienLayout.setVerticalGroup(
            pnlHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHocVienLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblIconHV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHocVien)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMain.add(pnlHocVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 150, 130));

        pnlKhoaHoc.setBackground(new java.awt.Color(0, 245, 232));
        pnlKhoaHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKhoaHocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKhoaHocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKhoaHocMouseExited(evt);
            }
        });

        lblIconKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-khoahoc.png"))); // NOI18N

        lblKhoaHoc.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        lblKhoaHoc.setForeground(new java.awt.Color(255, 102, 0));
        lblKhoaHoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhoaHoc.setText("Khoá học");

        javax.swing.GroupLayout pnlKhoaHocLayout = new javax.swing.GroupLayout(pnlKhoaHoc);
        pnlKhoaHoc.setLayout(pnlKhoaHocLayout);
        pnlKhoaHocLayout.setHorizontalGroup(
            pnlKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhoaHocLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblIconKH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(pnlKhoaHocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKhoaHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlKhoaHocLayout.setVerticalGroup(
            pnlKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhoaHocLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblIconKH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKhoaHoc)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMain.add(pnlKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 150, 130));

        pnlThongKe.setBackground(new java.awt.Color(0, 245, 232));
        pnlThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseExited(evt);
            }
        });

        lblIconTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-thongke.png"))); // NOI18N

        lblThongKe.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(255, 102, 0));
        lblThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKe.setText("Thống kê");

        javax.swing.GroupLayout pnlThongKeLayout = new javax.swing.GroupLayout(pnlThongKe);
        pnlThongKe.setLayout(pnlThongKeLayout);
        pnlThongKeLayout.setHorizontalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongKeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblIconTK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(pnlThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlThongKeLayout.setVerticalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongKeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblIconTK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThongKe)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMain.add(pnlThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 150, 130));

        pnlDoiMK.setBackground(new java.awt.Color(0, 245, 232));
        pnlDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDoiMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDoiMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDoiMKMouseExited(evt);
            }
        });

        lblIconDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-doimk.png"))); // NOI18N

        lblDoiMK.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        lblDoiMK.setForeground(new java.awt.Color(255, 102, 0));
        lblDoiMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoiMK.setText("Đổi mật khẩu");

        javax.swing.GroupLayout pnlDoiMKLayout = new javax.swing.GroupLayout(pnlDoiMK);
        pnlDoiMK.setLayout(pnlDoiMKLayout);
        pnlDoiMKLayout.setHorizontalGroup(
            pnlDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoiMKLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblIconDMK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlDoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDoiMK, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDoiMKLayout.setVerticalGroup(
            pnlDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoiMKLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblIconDMK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDoiMK)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMain.add(pnlDoiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 150, 130));

        pnlDangXuat.setBackground(new java.awt.Color(0, 245, 232));
        pnlDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDangXuatMouseExited(evt);
            }
        });

        lblDX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-dangxuat.png"))); // NOI18N

        lblDangXuat.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(255, 102, 0));
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setText("Đăng xuất");

        javax.swing.GroupLayout pnlDangXuatLayout = new javax.swing.GroupLayout(pnlDangXuat);
        pnlDangXuat.setLayout(pnlDangXuatLayout);
        pnlDangXuatLayout.setHorizontalGroup(
            pnlDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDangXuatLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lblDX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(pnlDangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDangXuatLayout.setVerticalGroup(
            pnlDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDangXuatLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblDX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDangXuat)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMain.add(pnlDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 150, 130));

        pnlKetThuc.setBackground(new java.awt.Color(0, 245, 232));
        pnlKetThuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKetThucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKetThucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKetThucMouseExited(evt);
            }
        });

        lblIconKT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-ketthuc.png"))); // NOI18N

        lblKetThuc.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        lblKetThuc.setForeground(new java.awt.Color(255, 102, 0));
        lblKetThuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKetThuc.setText("Kết thúc");

        javax.swing.GroupLayout pnlKetThucLayout = new javax.swing.GroupLayout(pnlKetThuc);
        pnlKetThuc.setLayout(pnlKetThucLayout);
        pnlKetThucLayout.setHorizontalGroup(
            pnlKetThucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKetThucLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lblIconKT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKetThucLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlKetThucLayout.setVerticalGroup(
            pnlKetThucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKetThucLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblIconKT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKetThuc)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMain.add(pnlKetThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 150, 130));

        pnlGioiThieu.setBackground(new java.awt.Color(0, 245, 232));
        pnlGioiThieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGioiThieuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlGioiThieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlGioiThieuMouseExited(evt);
            }
        });

        lblIconGT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-gioithieu.png"))); // NOI18N

        lblGioiThieu.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        lblGioiThieu.setForeground(new java.awt.Color(255, 102, 0));
        lblGioiThieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGioiThieu.setText("Giới thiệu");

        javax.swing.GroupLayout pnlGioiThieuLayout = new javax.swing.GroupLayout(pnlGioiThieu);
        pnlGioiThieu.setLayout(pnlGioiThieuLayout);
        pnlGioiThieuLayout.setHorizontalGroup(
            pnlGioiThieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGioiThieuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblIconGT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(pnlGioiThieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGioiThieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlGioiThieuLayout.setVerticalGroup(
            pnlGioiThieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGioiThieuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblIconGT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGioiThieu)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMain.add(pnlGioiThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 150, 130));

        pnlDongHo.setBackground(new java.awt.Color(0, 245, 232));

        lblIconTG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icons/icons8-thoigian.png"))); // NOI18N

        lblDongHo.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 102, 0));
        lblDongHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDongHo.setText("Giờ");

        javax.swing.GroupLayout pnlDongHoLayout = new javax.swing.GroupLayout(pnlDongHo);
        pnlDongHo.setLayout(pnlDongHoLayout);
        pnlDongHoLayout.setHorizontalGroup(
            pnlDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDongHoLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lblIconTG, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDongHoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDongHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDongHoLayout.setVerticalGroup(
            pnlDongHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDongHoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblIconTG, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDongHo)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlMain.add(pnlDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, 150, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseClicked
        // TODO add your handling code here:
        this.openNhanVien();
    }//GEN-LAST:event_pnlNhanVienMouseClicked

    private void pnlChuyenDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChuyenDeMouseClicked
        // TODO add your handling code here:
        this.openChuyenDe();
    }//GEN-LAST:event_pnlChuyenDeMouseClicked

    private void pnlNguoiHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNguoiHocMouseClicked
        // TODO add your handling code here:
        this.openNguoiHoc();
    }//GEN-LAST:event_pnlNguoiHocMouseClicked

    private void pnlHocVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHocVienMouseClicked
        // TODO add your handling code here:
        this.openHocVien();
    }//GEN-LAST:event_pnlHocVienMouseClicked

    private void pnlKhoaHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhoaHocMouseClicked
        // TODO add your handling code here:
        this.openKhoaHoc();
    }//GEN-LAST:event_pnlKhoaHocMouseClicked

    private void pnlThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseClicked
        // TODO add your handling code here:
        this.openThongKe(0);
    }//GEN-LAST:event_pnlThongKeMouseClicked

    private void pnlDoiMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoiMKMouseClicked
        // TODO add your handling code here:
        this.openDoiMatKhau();
    }//GEN-LAST:event_pnlDoiMKMouseClicked

    private void pnlDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDangXuatMouseClicked
        // TODO add your handling code here:
        this.logout();
    }//GEN-LAST:event_pnlDangXuatMouseClicked

    private void pnlNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseEntered
        // TODO add your handling code here:
        setColor(pnlNhanVien);
        setFore(lblNhanVien);
    }//GEN-LAST:event_pnlNhanVienMouseEntered

    private void pnlNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseExited
        // TODO add your handling code here:
        resetColor(pnlNhanVien);
        resetFore(lblNhanVien);
    }//GEN-LAST:event_pnlNhanVienMouseExited

    private void pnlChuyenDeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChuyenDeMouseEntered
        // TODO add your handling code here:
        setColor(pnlChuyenDe);
        setFore(lblChuyenDe);
    }//GEN-LAST:event_pnlChuyenDeMouseEntered

    private void pnlChuyenDeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChuyenDeMouseExited
        // TODO add your handling code here:
        resetColor(pnlChuyenDe);
        resetFore(lblChuyenDe);
    }//GEN-LAST:event_pnlChuyenDeMouseExited

    private void pnlNguoiHocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNguoiHocMouseEntered
        // TODO add your handling code here:
        setColor(pnlNguoiHoc);
        setFore(lblNguoiHoc);
    }//GEN-LAST:event_pnlNguoiHocMouseEntered

    private void pnlNguoiHocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNguoiHocMouseExited
        // TODO add your handling code here:
        resetColor(pnlNguoiHoc);
        resetFore(lblNguoiHoc);
    }//GEN-LAST:event_pnlNguoiHocMouseExited

    private void pnlHocVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHocVienMouseEntered
        // TODO add your handling code here:
        setColor(pnlHocVien);
        setFore(lblHocVien);
    }//GEN-LAST:event_pnlHocVienMouseEntered

    private void pnlHocVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHocVienMouseExited
        // TODO add your handling code here:
        resetColor(pnlHocVien);
        resetFore(lblHocVien);
    }//GEN-LAST:event_pnlHocVienMouseExited

    private void pnlKhoaHocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhoaHocMouseEntered
        // TODO add your handling code here:
        setColor(pnlKhoaHoc);
        setFore(lblKhoaHoc);
    }//GEN-LAST:event_pnlKhoaHocMouseEntered

    private void pnlKhoaHocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhoaHocMouseExited
        // TODO add your handling code here:
        resetColor(pnlKhoaHoc);
        resetFore(lblKhoaHoc);
    }//GEN-LAST:event_pnlKhoaHocMouseExited

    private void pnlThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseEntered
        // TODO add your handling code here:
        setColor(pnlThongKe);
        setFore(lblThongKe);
    }//GEN-LAST:event_pnlThongKeMouseEntered

    private void pnlThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseExited
        // TODO add your handling code here:
        resetColor(pnlThongKe);
        resetFore(lblThongKe);
    }//GEN-LAST:event_pnlThongKeMouseExited

    private void pnlDoiMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoiMKMouseEntered
        // TODO add your handling code here:
        setColor(pnlDoiMK);
        setFore(lblDoiMK);
    }//GEN-LAST:event_pnlDoiMKMouseEntered

    private void pnlDoiMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoiMKMouseExited
        // TODO add your handling code here:
        resetColor(pnlDoiMK);
        resetFore(lblDoiMK);
    }//GEN-LAST:event_pnlDoiMKMouseExited

    private void pnlDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDangXuatMouseEntered
        // TODO add your handling code here:
        setColor(pnlDangXuat);
        setFore(lblDangXuat);
    }//GEN-LAST:event_pnlDangXuatMouseEntered

    private void pnlDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDangXuatMouseExited
        // TODO add your handling code here:
        resetColor(pnlDangXuat);
        resetFore(lblDangXuat);
    }//GEN-LAST:event_pnlDangXuatMouseExited

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        if (evt.isPopupTrigger()) {
            popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseReleased

    private void pnlGioiThieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGioiThieuMouseClicked
        // TODO add your handling code here:
        this.openGioiThieu();
    }//GEN-LAST:event_pnlGioiThieuMouseClicked

    private void pnlGioiThieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGioiThieuMouseEntered
        // TODO add your handling code here:
        setColor(pnlGioiThieu);
        setFore(lblGioiThieu);
    }//GEN-LAST:event_pnlGioiThieuMouseEntered

    private void pnlGioiThieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGioiThieuMouseExited
        // TODO add your handling code here:
        resetColor(pnlGioiThieu);
        resetFore(lblGioiThieu);
    }//GEN-LAST:event_pnlGioiThieuMouseExited

    private void pnlKetThucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKetThucMouseClicked
        // TODO add your handling code here:
        this.exit();
    }//GEN-LAST:event_pnlKetThucMouseClicked

    private void pnlKetThucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKetThucMouseEntered
        // TODO add your handling code here:
        setColor(pnlKetThuc);
        setFore(lblKetThuc);
    }//GEN-LAST:event_pnlKetThucMouseEntered

    private void pnlKetThucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKetThucMouseExited
        // TODO add your handling code here:
        resetColor(pnlKetThuc);
        resetFore(lblKetThuc);
    }//GEN-LAST:event_pnlKetThucMouseExited

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblTenNV.setText("Nhân viên: " + XAuth.user.getMaNV());
        lblVaiTro.setText("Vai trò: " + String.valueOf(XAuth.user.isVaiTro() ? "Trưởng phòng" : "Nhân viên"));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem RightClick;
    private javax.swing.JLabel lblChuyenDe;
    private javax.swing.JLabel lblDX;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblDoiMK;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGioiThieu;
    private javax.swing.JLabel lblHocVien;
    private javax.swing.JLabel lblIconCD;
    private javax.swing.JLabel lblIconDMK;
    private javax.swing.JLabel lblIconGT;
    private javax.swing.JLabel lblIconHV;
    private javax.swing.JLabel lblIconKH;
    private javax.swing.JLabel lblIconKT;
    private javax.swing.JLabel lblIconNN;
    private javax.swing.JLabel lblIconNV;
    private javax.swing.JLabel lblIconTG;
    private javax.swing.JLabel lblIconTK;
    private javax.swing.JLabel lblKetThuc;
    private javax.swing.JLabel lblKhoaHoc;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNguoiHoc;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblPoly;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JPanel pnlChuyenDe;
    private javax.swing.JPanel pnlDangXuat;
    private javax.swing.JPanel pnlDoiMK;
    private javax.swing.JPanel pnlDongHo;
    private javax.swing.JPanel pnlGioiThieu;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHocVien;
    private javax.swing.JPanel pnlKetThuc;
    private javax.swing.JPanel pnlKhoaHoc;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNguoiHoc;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
